name: Build & Deploy (Production)]
on: 
  push:
    branches:
      - master
    paths:
      - packages/server/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v2